language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

# see https://github.com/travis-ci/travis-ci/issues/8408
before_install:
- unset _JAVA_OPTIONS

install: echo "The default Travis install script is being skipped!"

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.m2

script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B
