/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.facebook.ktfmt.format

import com.facebook.ktfmt.format.TrailingCommaManagementStrategy.COMPLETE
import com.facebook.ktfmt.format.TrailingCommaManagementStrategy.NONE

data class FormattingOptions(
    /** ktfmt breaks lines longer than maxWidth. */
    val maxWidth: Int = DEFAULT_MAX_WIDTH,

    /**
     * blockIndent is the size of the indent used when a new block is opened, in spaces.
     *
     * For example,
     * ```
     * fun f() {
     *   //
     * }
     * ```
     */
    val blockIndent: Int,

    /**
     * continuationIndent is the size of the indent used when a line is broken because it's too
     * long, in spaces.
     *
     * For example,
     * ```
     * val foo = bar(
     *     1)
     * ```
     */
    val continuationIndent: Int,

    /**
     * Strategy for managing trailing commas.
     *
     * See [TrailingCommaManagementStrategy] for more details.
     */
    val trailingCommaManagementStrategy: TrailingCommaManagementStrategy = COMPLETE,

    /** Whether ktfmt should remove imports that are not used. */
    val removeUnusedImports: Boolean = true,

    /**
     * Whether to preserve user-authored line breaks inside lambda bodies. Enabled by default.
     *
     * When enabled, a lambda whose body spans multiple lines in the source is kept multi-line. A
     * lambda that fits on a single line in the source is left alone. This is general-purpose and
     * lets callers preserve structure they care about without ktfmt prescribing a specific outcome.
     *
     * For example, with this option enabled, the following stays multi-line:
     * ```
     * App {
     *   SelectableCard {
     *     Button { Text("Hello") }
     *   }
     * }
     * ```
     *
     * While this stays single-line:
     * ```
     * App { SelectableCard { Button { Text("Hello") } } }
     * ```
     */
    val preserveLambdaBreaks: Boolean = true,

    /**
     * Print the Ops generated by KotlinInputAstVisitor to help reason about formatting (i.e.,
     * newline) decisions
     */
    val debuggingPrintOpsAfterFormatting: Boolean = false,
) {
  companion object {
    const val DEFAULT_MAX_WIDTH: Int = 100
    const val DEFAULT_BLOCK_INDENT: Int = 2
    const val DEFAULT_CONTINUATION_INDENT: Int = 4
  }

  @Deprecated("Here just for retrocompatibility reasons. Will be removed on 1.0.0")
  constructor(
      maxWidth: Int,
      blockIndent: Int,
      continuationIndent: Int,
      manageTrailingCommas: Boolean = true,
      removeUnusedImports: Boolean = true,
      debuggingPrintOpsAfterFormatting: Boolean = false,
  ) : this(
      maxWidth = maxWidth,
      blockIndent = blockIndent,
      continuationIndent = continuationIndent,
      trailingCommaManagementStrategy = if (manageTrailingCommas) COMPLETE else NONE,
      removeUnusedImports = removeUnusedImports,
      // Pinned to false to preserve the behavior callers of this deprecated constructor had before
      // preserveLambdaBreaks existed and became the default.
      preserveLambdaBreaks = false,
      debuggingPrintOpsAfterFormatting = debuggingPrintOpsAfterFormatting,
  )

  @Deprecated("Here just for retrocompatibility reasons. Will be removed on 1.0.0")
  constructor(
      maxWidth: Int,
      blockIndent: Int,
      continuationIndent: Int,
      trailingCommaManagementStrategy: TrailingCommaManagementStrategy,
      removeUnusedImports: Boolean,
      debuggingPrintOpsAfterFormatting: Boolean,
  ) : this(
      maxWidth = maxWidth,
      blockIndent = blockIndent,
      continuationIndent = continuationIndent,
      trailingCommaManagementStrategy = trailingCommaManagementStrategy,
      removeUnusedImports = removeUnusedImports,
      // Set to false to preserve the behavior callers of this deprecated constructor had before
      // preserveLambdaBreaks existed and became the default.
      preserveLambdaBreaks = false,
      debuggingPrintOpsAfterFormatting = debuggingPrintOpsAfterFormatting,
  )

  internal val manageTrailingCommas: Boolean
    get() = trailingCommaManagementStrategy != NONE

  /**
   * Returns a [Builder] pre-populated with this instance's values.
   *
   * Handy for deriving a new [FormattingOptions] from an existing one (such as one of the
   * [Formatter] presets) while overriding only a few fields.
   */
  fun toBuilder(): Builder =
      Builder()
          .maxWidth(maxWidth)
          .blockIndent(blockIndent)
          .continuationIndent(continuationIndent)
          .trailingCommaManagementStrategy(trailingCommaManagementStrategy)
          .removeUnusedImports(removeUnusedImports)
          .preserveLambdaBreaks(preserveLambdaBreaks)
          .debuggingPrintOpsAfterFormatting(debuggingPrintOpsAfterFormatting)

  /**
   * A fluent builder for [FormattingOptions].
   *
   * Prefer this (or [toBuilder]) over the constructor and generated [copy] when constructing
   * options from outside this module. New options can be introduced as additional builder methods
   * without breaking source or binary compatibility for existing callers, which is not true of the
   * constructor or [copy] overloads.
   *
   * For example:
   * ```
   * val options =
   *     FormattingOptions.Builder()
   *         .blockIndent(2)
   *         .continuationIndent(4)
   *         .preserveLambdaBreaks(true)
   *         .build()
   * ```
   */
  class Builder {
    private var maxWidth: Int = DEFAULT_MAX_WIDTH
    private var blockIndent: Int = DEFAULT_BLOCK_INDENT
    private var continuationIndent: Int = DEFAULT_CONTINUATION_INDENT
    private var trailingCommaManagementStrategy: TrailingCommaManagementStrategy = COMPLETE
    private var removeUnusedImports: Boolean = true
    private var preserveLambdaBreaks: Boolean = true
    private var debuggingPrintOpsAfterFormatting: Boolean = false

    /** @see FormattingOptions.maxWidth */
    fun maxWidth(maxWidth: Int): Builder = apply { this.maxWidth = maxWidth }

    /** @see FormattingOptions.blockIndent */
    fun blockIndent(blockIndent: Int): Builder = apply { this.blockIndent = blockIndent }

    /** @see FormattingOptions.continuationIndent */
    fun continuationIndent(continuationIndent: Int): Builder = apply {
      this.continuationIndent = continuationIndent
    }

    /** @see FormattingOptions.trailingCommaManagementStrategy */
    fun trailingCommaManagementStrategy(
        trailingCommaManagementStrategy: TrailingCommaManagementStrategy,
    ): Builder = apply { this.trailingCommaManagementStrategy = trailingCommaManagementStrategy }

    /** @see FormattingOptions.removeUnusedImports */
    fun removeUnusedImports(removeUnusedImports: Boolean): Builder = apply {
      this.removeUnusedImports = removeUnusedImports
    }

    /** @see FormattingOptions.preserveLambdaBreaks */
    fun preserveLambdaBreaks(preserveLambdaBreaks: Boolean): Builder = apply {
      this.preserveLambdaBreaks = preserveLambdaBreaks
    }

    /** @see FormattingOptions.debuggingPrintOpsAfterFormatting */
    fun debuggingPrintOpsAfterFormatting(debuggingPrintOpsAfterFormatting: Boolean): Builder =
        apply {
          this.debuggingPrintOpsAfterFormatting = debuggingPrintOpsAfterFormatting
        }

    /** Builds a new [FormattingOptions] from the current builder state. */
    fun build(): FormattingOptions =
        FormattingOptions(
            maxWidth = maxWidth,
            blockIndent = blockIndent,
            continuationIndent = continuationIndent,
            trailingCommaManagementStrategy = trailingCommaManagementStrategy,
            removeUnusedImports = removeUnusedImports,
            preserveLambdaBreaks = preserveLambdaBreaks,
            debuggingPrintOpsAfterFormatting = debuggingPrintOpsAfterFormatting,
        )
  }
}

enum class TrailingCommaManagementStrategy(
    val removeRedundantTrailingCommas: Boolean,
) {
  /** Do not manage trailing commas at all, only format what is already present */
  NONE(removeRedundantTrailingCommas = false),

  /**
   * Only add trailing commas when necessary, but do not remove them.
   *
   * Lists that cannot fit on one line will have trailing commas inserted. Trailing commas can to be
   * used to "hint" ktfmt that the list should be broken to multiple lines.
   */
  ONLY_ADD(removeRedundantTrailingCommas = false),

  /**
   * Fully manage trailing commas, adding and removing them where necessary.
   *
   * Lists that cannot fit on one line will have trailing commas inserted. Lists that span multiple
   * lines will have them removed. Manually inserted trailing commas cannot be used as a hint to
   * force breaking lists to multiple lines.
   */
  COMPLETE(removeRedundantTrailingCommas = true),
  ;

  override fun toString(): String {
    // NONE -> "None"
    // ONLY_ADD -> "Only add"
    // COMPLETE -> "Complete"
    return name.replace("_", " ").lowercase().replaceFirstChar {
      if (it.isLowerCase()) it.titlecase() else it.toString()
    }
  }
}
